server:
  port: 9002
spring:
  rabbitmq:
    host: 192.168.44.130
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          ## 开启消费者重试
          enabled: true
          ##最大重试次数（默认无数次）
          max-attempts: 5
          ##重试间隔次数
          initial-interval: 3000